/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/otp/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request a login OTP for a phone number */
        post: operations["requestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify an OTP and start a session (sets an httpOnly cookie) */
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent calls for the authenticated org */
        get: operations["listCalls"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/calls/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A single call (org-scoped) */
        get: operations["getCall"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/call-policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The org's calling window + retry policy */
        get: operations["getCallPolicy"];
        /** Update the calling window + retry policy */
        put: operations["saveCallPolicy"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a message and get the assistant's reply */
        post: operations["sendChatMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connected messaging channels (WhatsApp / Messenger) */
        get: operations["listChannels"];
        put?: never;
        /** Connect a WhatsApp or Messenger channel */
        post: operations["connectChannel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/channels/{type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect a channel */
        delete: operations["disconnectChannel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chat/widget settings */
        get: operations["getChatSettings"];
        /** Update chat/widget settings */
        put: operations["saveChatSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The org's chat conversations */
        get: operations["listConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A conversation's messages */
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/conversations/{id}/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate (or refresh) the AI insight for a conversation
         * @description Distills the transcript into a summary, outcome, sentiment, and suggested next action. Provider-agnostic; the result is cached and returned on the conversation detail. Re-running overwrites the prior insight.
         */
        post: operations["summarizeConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/conversations/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Transition a conversation (open | handling | closed)
         * @description Setting "handling" hands the thread to a human — the assistant stops auto-replying so it doesn't talk over the agent. "open" returns it to the bot; "closed" ends it.
         */
        put: operations["setConversationStatus"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/conversations/{id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post a human agent's reply (takes the conversation over)
         * @description Records the agent's message (role "agent"), marks the conversation "handling", and delivers the reply out over the messaging channel (WhatsApp/Messenger). Web-widget threads have no external transport.
         */
        post: operations["agentReply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The org's campaigns */
        get: operations["listCampaigns"];
        put?: never;
        /** Create a draft campaign */
        post: operations["createCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{id}/recipients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import a recipient list from CSV (phone[,name] per row)
         * @description Rows with an invalid phone (including a header row) are skipped; phones are normalized and deduped. A campaign with recipients dials that list; one with none falls back to all callable customers.
         */
        post: operations["importCampaignRecipients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schedule a draft campaign to auto-start at a future time */
        post: operations["scheduleCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/campaigns/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dispatch the campaign now (recipients, or all callable customers) */
        post: operations["startCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The org's customers */
        get: operations["listCustomers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customers/{id}/dnd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Put a customer on do-not-disturb (skip calls) */
        post: operations["setDnd"];
        /** Remove a customer from do-not-disturb */
        delete: operations["clearDnd"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The org's flows */
        get: operations["listFlows"];
        put?: never;
        /**
         * Create a flow (no-code builder / templates)
         * @description Names are unique per org among active flows, so ingest can route an event type to a flow by name (e.g. cart_abandoned → cart_recovery).
         */
        post: operations["createFlow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flows/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Built-in starter flows the no-code builder can clone */
        get: operations["listFlowTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flows/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dry-run an IVR spec against keypad inputs (in-browser simulator)
         * @description Runs the deterministic IVR engine over a spec and a sequence of inputs (each a digit or the literal "timeout"), returning every step and the terminal outcome. No telephony, credits, or persistence.
         */
        post: operations["simulateFlow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/flows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A flow with its spec (for the builder) */
        get: operations["getFlow"];
        /** Replace a flow's spec */
        put: operations["updateFlow"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Credit balance and recent ledger */
        get: operations["getBilling"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/billing/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add credits to the org balance */
        post: operations["topUpCredits"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard metrics rollup */
        get: operations["getSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cross-channel dashboard rollup (calls, conversations, credits) */
        get: operations["getAnalyticsOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask a natural-language question over your metrics (AI custom reports)
         * @description Provider-agnostic. Returns a plain-language answer grounded in the org's current call, conversation, and credit metrics, plus the underlying data.
         */
        post: operations["askReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dev/test-call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate a call with a keypress (no telephony) — generates an outcome */
        post: operations["testCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rename the org (store) shown in the dashboard */
        put: operations["renameOrg"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/publishable-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mint a publishable (yvr_pk_) key for the embeddable widget */
        post: operations["createPublishableKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the org's API keys (metadata only) */
        get: operations["listApiKeys"];
        put?: never;
        /** Create an API key for the org (returned once) */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current webhook config (no secret) */
        get: operations["getWebhook"];
        put?: never;
        /** Set the webhook URL; returns a fresh signing secret once */
        post: operations["setWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a merchant store event (routes to the matching flow) */
        post: operations["ingestEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        Status: {
            status: string;
        };
        OtpRequest: {
            /** @example 01712345678 */
            phone: string;
        };
        OtpRequestResult: {
            status: string;
            /** @description Present only in dev (no SMS provider yet) */
            dev_code?: string;
        };
        OtpVerify: {
            phone: string;
            code: string;
        };
        SessionUser: {
            user_id: string;
            phone: string;
        };
        Me: {
            user_id: string;
            phone: string;
            email: string;
            name: string;
            org: {
                id: string;
                name: string;
            };
        };
        Summary: {
            total: number;
            confirmed: number;
            cancelled: number;
            today: number;
            /** @description percent 0-100 */
            confirmation_rate: number;
        };
        AnalyticsOverview: {
            calls: {
                total: number;
                confirmed: number;
                cancelled: number;
                today: number;
                /** @description percent 0-100 */
                confirmation_rate: number;
            };
            conversations: {
                total: number;
                today: number;
                resolved: number;
                pending: number;
                sale: number;
                needs_human: number;
                /** @description percent 0-100 */
                resolution_rate: number;
            };
            credits: {
                balance: number;
                spent_today: number;
                spent_30d: number;
            };
        };
        CallPolicy: {
            /** @description local hour calls may start, inclusive (0-23) */
            window_start: number;
            /** @description local hour calls must stop, exclusive (1-24) */
            window_end: number;
            /** @example Asia/Dhaka */
            timezone: string;
            /** @description retry attempts for a failed call (0-10) */
            max_retries: number;
        };
        TestCallRequest: {
            phone: string;
            /** @description simulated keypress: 1|2|3 */
            digit?: string;
        };
        TestCallResult: {
            call_id: string;
            status: string;
            result: string;
        };
        ApiKeyResult: {
            api_key: string;
        };
        ApiKeyInfo: {
            prefix: string;
            name: string;
            /** @enum {string} */
            kind: "secret" | "publishable";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at?: string | null;
        };
        ApiKeyList: {
            keys: components["schemas"]["ApiKeyInfo"][];
        };
        WebhookConfig: {
            configured: boolean;
            url?: string;
            events: string[];
        };
        WebhookSet: {
            url: string;
            events?: string[];
        };
        WebhookSecret: {
            secret: string;
        };
        LedgerEntry: {
            delta: number;
            reason: string;
            /** Format: date-time */
            created_at: string;
        };
        Billing: {
            balance: number;
            ledger: components["schemas"]["LedgerEntry"][];
        };
        Channel: {
            type: string;
            external_id: string;
            /** Format: date-time */
            created_at: string;
        };
        ChannelList: {
            channels: components["schemas"]["Channel"][];
        };
        ChatSettings: {
            instructions: string;
            widget_title: string;
            welcome: string;
            accent: string;
        };
        Conversation: {
            id: string;
            channel: string;
            customer: string;
            status: string;
            last_message: string;
            message_count: number;
            /** Format: date-time */
            updated_at: string;
        };
        ConversationList: {
            conversations: components["schemas"]["Conversation"][];
        };
        ChatMessage: {
            /** @enum {string} */
            role: "user" | "assistant" | "agent" | "system";
            content: string;
            /** Format: date-time */
            created_at: string;
        };
        MessageList: {
            messages: components["schemas"]["ChatMessage"][];
            /** @description The cached AI insight, present once one has been generated. */
            insight?: components["schemas"]["ConversationInsight"] | null;
        };
        ConversationInsight: {
            summary: string;
            /** @enum {string} */
            outcome: "resolved" | "pending" | "sale" | "needs_human" | "unknown";
            /** @enum {string} */
            sentiment: "positive" | "neutral" | "negative";
            next_action: string;
            /** Format: date-time */
            created_at: string;
        };
        Campaign: {
            id: string;
            name: string;
            /** @enum {string} */
            status: "draft" | "scheduled" | "completed";
            target_count: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            scheduled_at?: string | null;
        };
        CampaignList: {
            campaigns: components["schemas"]["Campaign"][];
        };
        Customer: {
            id: string;
            phone: string;
            name: string;
            dnd: boolean;
            /** Format: date-time */
            created_at: string;
        };
        CustomerList: {
            customers: components["schemas"]["Customer"][];
        };
        FlowSummary: {
            id: string;
            name: string;
            version: number;
            channel: string;
            type: string;
            active: boolean;
        };
        FlowList: {
            flows: components["schemas"]["FlowSummary"][];
        };
        FlowDetail: {
            id: string;
            name: string;
            version: number;
            channel: string;
            type: string;
            locale: string;
            spec: {
                [key: string]: unknown;
            };
        };
        Call: {
            id: string;
            /** @enum {string} */
            direction: "inbound" | "outbound";
            /** @enum {string} */
            status: "queued" | "ringing" | "in_progress" | "completed" | "failed" | "no_answer";
            result: string;
            /** Format: date-time */
            created_at: string;
        };
        CallList: {
            calls: components["schemas"]["Call"][];
        };
        CallDetail: {
            id: string;
            direction: string;
            status: string;
            result: string;
            flow_id: string;
            provider_call_id: string;
            /** Format: date-time */
            created_at: string;
        };
        EventRequest: {
            /**
             * @description Routed to a flow by name: order_placed→order_confirm, abandoned_cart→cart_recovery, out_for_delivery→delivery_reminder. Other types are stored but trigger no call.
             * @enum {string}
             */
            event_type: "order_placed" | "order_cancelled" | "abandoned_cart" | "out_for_delivery";
            /** @description Merchant-side unique id (idempotency) */
            event_id: string;
            customer?: {
                phone?: string;
            };
        };
        EventAccepted: {
            status: string;
            event_id: string;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequest"];
            };
        };
        responses: {
            /** @description Code sent (dev_code present only in dev) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpRequestResult"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerify"];
            };
        };
        responses: {
            /** @description Verified; session cookie set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionUser"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listCalls: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Calls, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Call detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["BadRequest"];
        };
    };
    getCallPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Call policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallPolicy"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    saveCallPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallPolicy"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    sendChatMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Omit to start a new conversation */
                    conversation_id?: string;
                    text: string;
                };
            };
        };
        responses: {
            /** @description Reply */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        conversation_id: string;
                        reply: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listChannels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Channels */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    connectChannel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    type: "whatsapp" | "messenger";
                    /** @description WhatsApp phone_number_id or Messenger page_id */
                    external_id: string;
                    access_token: string;
                    verify_token: string;
                };
            };
        };
        responses: {
            /** @description Connected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    disconnectChannel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getChatSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSettings"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    saveChatSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatSettings"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Messages */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["BadRequest"];
        };
    };
    summarizeConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The generated insight */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationInsight"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["BadRequest"];
        };
    };
    setConversationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "open" | "handling" | "closed";
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["BadRequest"];
        };
    };
    agentReply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    text: string;
                };
            };
        };
        responses: {
            /** @description Stored (and delivered when the channel supports it) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        delivered?: boolean;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["BadRequest"];
        };
    };
    listCampaigns: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaigns */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    importCampaignRecipients: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "text/csv": string;
            };
        };
        responses: {
            /** @description Imported */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        added: number;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["BadRequest"];
        };
    };
    scheduleCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: date-time
                     * @description RFC3339, must be in the future
                     */
                    at: string;
                };
            };
        };
        responses: {
            /** @description Scheduled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                        /** Format: date-time */
                        at?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["BadRequest"];
        };
    };
    startCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        queued: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["BadRequest"];
        };
    };
    listCustomers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Customers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    setDnd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DND set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        dnd?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    clearDnd: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DND cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        dnd?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listFlows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flows */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createFlow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example cart_recovery */
                    name: string;
                    /**
                     * @default ivr
                     * @enum {string}
                     */
                    type: "ivr" | "chat";
                    /** @enum {string} */
                    channel?: "voice" | "chat";
                    /** @default en */
                    locale?: string;
                    /** @description IVR keypad spec (required for type=ivr) */
                    spec?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description A flow with that name already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listFlowTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        templates: {
                            name?: string;
                            title?: string;
                            description?: string;
                            channel?: string;
                            type?: string;
                            locale?: string;
                            spec?: {
                                [key: string]: unknown;
                            };
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    simulateFlow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    spec: {
                        [key: string]: unknown;
                    };
                    inputs?: string[];
                };
            };
        };
        responses: {
            /** @description Simulation trace + outcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ended: boolean;
                        result?: string;
                        status?: string;
                        steps: {
                            node?: string;
                            /** @enum {string} */
                            kind?: "say" | "say_gather" | "hangup";
                            awaits_input?: boolean;
                            say?: {
                                [key: string]: unknown;
                            };
                        }[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getFlow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flow detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["BadRequest"];
        };
    };
    updateFlow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    spec: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getBilling: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Billing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Billing"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    topUpCredits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    amount?: number;
                };
            };
        };
        responses: {
            /** @description New balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        balance: number;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAnalyticsOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOverview"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    askReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example which channel recovered the most this week? */
                    question: string;
                };
            };
        };
        responses: {
            /** @description Answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        answer: string;
                        data: components["schemas"]["AnalyticsOverview"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    testCall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestCallRequest"];
            };
        };
        responses: {
            /** @description Simulated call outcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCallResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    renameOrg: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                };
            };
        };
        responses: {
            /** @description Renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createPublishableKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Publishable key (shown once) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new key (store it now — not retrievable later) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Webhook config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookConfig"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    setWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookSet"];
            };
        };
        responses: {
            /** @description Saved; signing secret (store it now) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSecret"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    ingestEvent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description Duplicate (idempotent no-op) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
